"""empty message

Revision ID: 3b33593e8009
Revises: b84cbc30e981
Create Date: 2019-08-25 17:56:48.559867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b33593e8009'
down_revision = 'b84cbc30e981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rss_entry', ['href'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rss_entry', type_='unique')
    # ### end Alembic commands ###
